b=[1 0];
k=0;
a=[1 -k];
[H,w]=freqz(b,a,1000,'whole');
Hm=abs(H);
subplot(321);
plot(w,Hm),grid on;
xlabel('w rad/s'),ylabel('Hm');
Hp=angle(H);
subplot(322);
plot(w,Hp),grid on;
xlabel('w rad/s'),ylabel('Phi');
k=0.5;
a=[1 -k];
[H,w]=freqz(b,a,1000,'whole');
Hm=abs(H);
subplot(323);
plot(w,Hm),grid on;
xlabel('w rad/s'),ylabel('Hm');
Hp=angle(H);
subplot(324);
plot(w,Hp),grid on;
xlabel('w rad/s'),ylabel('Phi');
k=1;
a=[1 -k];
[H,w]=freqz(b,a,1000,'whole');
Hm=abs(H);
subplot(325);
plot(w,Hm),grid on;
xlabel('w rad/s'),ylabel('Hm');
Hp=angle(H);
subplot(326);
plot(w,Hp),grid on;
xlabel('w rad/s'),ylabel('Phi');