a=[1 -1/3];
b=[1 0];
[H,w]=freqz(b,a,400,'whole');
Hm=abs(H);
Hp=angle(H);
subplot(211);
plot(w,Hm);
xlabel('\omega(rad/s)');ylabel('幅度');
title('幅频响应特性曲线');
subplot(212);plot(w,Hp);
xlabel('\omega(rad/s)');ylabel('相位');
title( '相频响应特性曲线');